# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorkFit
  pod 'Firebase'
  pod 'Firebase/Core'	#Inclui apenas Analytics
  pod 'Firebase/AdMob'	#AdMob
  pod 'Firebase/Messaging'	#Cloud Messaging / Notifications
  pod 'Firebase/Database'	#Realtime Database
  pod 'Firebase/Crash'	#Crash Reporting
  pod 'Firebase/RemoteConfig'	#Remote Config
  pod 'Firebase/Auth'	#Authentication
  pod 'Firebase/AppIndexing'	#App Indexingstall
  pod 'Firebase/Storage'#Storage
  pod 'UICircularProgressRing'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'WorkFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorkFitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
